### ISSUE TITLE
python 3.x issues

### ISSUE THREAD

**Issue by jchodera** [choderalab/alchemy#51]
I've encountered a failure for the Abl:imatinib explicit solvent YANK test system in Python 3.4:

```
Traceback (most recent call last):
  File "soften-ligand.py", line 77, in <module>
    factory = AbsoluteAlchemicalFactory(reference_system, ligand_atoms=alchemical_atoms, annihilate_electrostatics=True, annihilate_sterics=False)
  File "/cbio/jclab/home/chodera/miniconda3/envs/sams/lib/python3.4/site-packages/alchemy/alchemy.py", line 356, in __init__
    [self.alchemically_modified_system, self.force_labels] = self._createAlchemicallyModifiedSystem(self.reference_system)
  File "/cbio/jclab/home/chodera/miniconda3/envs/sams/lib/python3.4/site-packages/alchemy/alchemy.py", line 1480, in _createAlchemicallyModifiedSystem
    self._alchemicallyModifyNonbondedForce(system, reference_force, force_labels)
  File "/cbio/jclab/home/chodera/miniconda3/envs/sams/lib/python3.4/site-packages/alchemy/alchemy.py", line 1197, in _alchemicallyModifyNonbondedForce
    na_sterics_custom_nonbonded_force.addInteractionGroup(nonalchemical_atomset, alchemical_atomset)
  File "/cbio/jclab/home/chodera/miniconda3/envs/sams/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 9950, in addInteractionGroup
    return _openmm.CustomNonbondedForce_addInteractionGroup(self, set1, set2)
TypeError: in method 'CustomNonbondedForce_addInteractionGroup', argument 3 of type 'std::set< int,std::less< int >,std::allocator< int > > const &'
```

**Comment by jchodera** [comment]
I see the same behavior for Python 3.5

**Comment by jchodera** [comment]
This is the cause: https://github.com/pandegroup/openmm/issues/1650

**Comment by jchodera** [comment]
I'm fixing this now.
